name: CI
on:
  push: 
  workflow_dispatch: 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          
          - name: Login no Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
              
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
                push: true
                context: ./src
                file: ./src/Dockerfile
                tags: | 
                    fabricioveronez/python-web-app:${{ github.run_number }}
                    fabricioveronez/python-web-app:latest

          - name: Executar o scan de vulnerabilidade
            uses: aquasecurity/trivy-action@0.20.0
            with:
              image-ref: fabricioveronez/python-web-app:${{ github.run_number }}
              scan-type: image
              format: 'json'
              exit-code: 0
              output: 'resultado-trivy.json'
              severity: UNKNOWN,CRITICAL,HIGH,MEDIUM,LOW
          
          - name: Upload do arquivo de resultado do trivy
            uses: actions/upload-artifact@v4
            with:
              name: trivy
              path: resultado-trivy.json
