name: CI
on:
    push: 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          
          - name: Login no Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
              
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
                push: true
                context: ./src
                dockerfile: ./src/Dockerfile
                tags: | 
                    fabricioveronez/python-web-app:${{ github.run_number }}

          - name: Run Trivy vulnerability scanner
            uses: aquasecurity/trivy-action@0.20.0
            with:
              image-ref: fabricioveronez/python-web-app:${{ github.run_number }}
              format: 'sarif'
              output: 'trivy-results.sarif'

          - name: Upload Trivy scan results to GitHub Security tab
            uses: github/codeql-action/upload-sarif@v2
            with:
              sarif_file: 'trivy-results.sarif'
