name: CI
on:
    push: 
    workflow_dispatch: 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          
          - name: Login no Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
              
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
                push: true
                context: ./src
                file: ./src/Dockerfile
                tags: | 
                    fabricioveronez/python-web-app:${{ github.run_number }}
    scan:
      permissions:
        contents: read
        packages: write
        id-token: write
        security-events: write
        actions: read
      name: Scan da Imagem 
      uses: fabricioveronez/python-web/.github/workflows/scan.yml@main
      needs: [build]
      with:
        docker_image: fabricioveronez/python-web-app:${{ github.run_number }}
