name: Trivy Scan
on:
    workflow_call: 
      inputs:
        docker_image:
          required: true
          type: string
          description: "Tag da imagem que deve ser usada para escanear"
jobs:
    scan:
        permissions:
          contents: read
          packages: write
          id-token: write
          security-events: write
          actions: read
        runs-on: ubuntu-latest
        steps:
          - name: Run Trivy vulnerability scanner
            uses: aquasecurity/trivy-action@0.20.0
            with:
              image-ref: ${{ inputs.docker_image }}
              scan-type: image
              format: 'sarif'
              exit-code: 0
              output: 'trivy-results.sarif'
              severity: UNKNOWN,CRITICAL,HIGH,MEDIUM,LOW
          
          - name: Conteúdo do Trivy
            run: cat trivy-results.sarif

          - name: Upload Trivy scan results to GitHub Security tab
            uses: github/codeql-action/upload-sarif@v3
            with:
              sarif_file: 'trivy-results.sarif'
